const express = require('express');
const router = express.Router();
const authController = require('../controllers/authController');
const { verifyToken, verifyRole } = require("../middlewares/authMiddleware");
router.post('/register', authController.register);
router.post('/login', authController.login);
router.post('/logout', authController.logOut);
router.post("/refresh-token", authController.refreshToken);
router.put("/change-password", verifyToken, authController.changePassword);
module.exports = router;
